from colors import *

BACKGROUND = MARTE
FILL_MATRIX_ROCKS = 0.1
GEM_CENTERS = 20
GEM_RANGE = 3
GEM_FILL = 0.5
GAME_MATRIX_SIZE = 50
AGENT_NUMBER = 20
SPEED = 15
PHEROMONE_LIFE = 10

AGENT_PHEROMONE_EXPLOSION = 2
AGENT_PHEROMENE_EXPLOSION_LIFE = PHEROMONE_LIFE * 4
AGENT_MSHIP = 0.2
AGENT_DEFAULT = 0.45