from colors import *

BACKGROUND = MARTE
FILL_MATRIX_ROCKS = 0.10
GEM_CENTERS = 10
GEM_RANGE = 3
GEM_FILL = 1
GAME_MATRIX_SIZE = 50
AGENT_NUMBER = 50
SPEED = 20
PHEROMONE_LIFE = 25
PHEROMONE_PATH = False
CLEAR_MSHIP_AREA = True

AGENT_PHEROMONE_EXPLOSION = 3
AGENT_PHEROMENE_EXPLOSION_LIFE = PHEROMONE_LIFE
AGENT_MSHIP = 0.2
AGENT_RANDOM = 0.2
AGENT_DEFAULT_MAX_DISTANCE = 0.0